title: NeRFLight [CVPR 2023]
description: Fast and Light Neural Radiance Fields using a Shared Feature Grid
authors: Fernando Rivas-Manzaneque &nbsp;&nbsp; Jorge Sierra-Acosta &nbsp;&nbsp; Adrian Penate-Sanchez &nbsp;&nbsp; Francesc Moreno-Noguer &nbsp;&nbsp; Angela Ribeiro
code_url: https://github.com/Ediolot/nerflight
video_url: https://github.com/Ediolot/nerflight
paper_url: https://openaccess.thecvf.com/content/CVPR2023/html/Rivas-Manzaneque_NeRFLight_Fast_and_Light_Neural_Radiance_Fields_Using_a_Shared_CVPR_2023_paper.html
theme: jekyll-theme-cayman
